name: Build Armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      BOARD:
        description: 'Board'
        required: true
        default: '[nanopi-r4s]'
      BRANCH:
        description: 'Branch'
        required: true
        default: '[current],dev,legacy'
      RELEASE:
        description: 'Release'
        required: true
        default: '[bullseye],buster,hirsute,focal'
      BUILD_MINIMAL:
        description: 'Build minimal'
        required: true
        default: '[no],yes'
      FIXED_IMAGE_SIZE:
        description: 'Fixed image size'
        required: true
        default: '1024,[2048],3072,4096'

env:
  BOARD: ${{ github.event.inputs.BOARD }}
  BRANCH: ${{ github.event.inputs.BRANCH }}
  RELEASE: ${{ github.event.inputs.RELEASE }}
  BUILD_MINIMAL: ${{ github.event.inputs.BUILD_MINIMAL }}
  FIXED_IMAGE_SIZE: ${{ github.event.inputs.FIXED_IMAGE_SIZE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install tree
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Checkout Armbian build script
      uses: actions/checkout@v2
      with:
        repository: armbian/build
        path: build

    - name: Cache rootfs
      id: cache-rootfs
      uses: actions/cache@v2.1.6
      with:
        path: build/cache/rootfs
        key: ${{ runner.os }}-${{ github.event.inputs.BOARD }}-${{ github.event.inputs.BRANCH }}-${{ github.event.inputs.RELEASE }}-${{ github.run_id }}

    - name: Build Armbian
      id: build-armbian
      run: |
        cd build
        sudo ./compile.sh \
        BOARD=$BOARD \
        BRANCH=$BRANCH \
        RELEASE=$RELEASE \
        BUILD_MINIMAL=$BUILD_MINIMAL \
        BUILD_DESKTOP=no \
        KERNEL_ONLY=no \
        KERNEL_CONFIGURE=no \
        ROOTFS_TYPE=f2fs \
        FIXED_IMAGE_SIZE=$FIXED_IMAGE_SIZE \
        WIREGUARD=no
        echo "::set-output name=status::success"
        df -hT

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: steps.build-armbian.outputs.status != 'success'
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Upload output directory
      uses: actions/upload-artifact@main
      if: steps.build-armbian.outputs.status == 'success'
      with:
        name: Armbian_Output
        path: build/output/images

    - name: Send complete notification
      if: steps.build-armbian.outputs.status == 'success'
      run: |
        curl -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}", "text": "✅ [${{ github.event.inputs.BOARD }}] Armbian编译完成"}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
